spring.application.name=backend
spring.security.user.name=admin
spring.security.user.password=admin

# DataSource + Flyway configuration.
# - In Docker, set env vars: SPRING_DATASOURCE_URL / _USERNAME / _PASSWORD
# - Locally, the defaults below point to the local Postgres (adjust as needed).

# todo: add env example and how to export, first check if its possible on windows 
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:myuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration